### ISSUE TITLE
Copying data failing but no error triggered

### ISSUE THREAD

**Issue by Dhruv-Garg79** [brianc/node-pg-copy-streams#153]
I am using this library to write data from bunch of CSVs to postgres database hosted on RDS.
node version = v14.19.0

sample code:
```
public async copyFromCsv(csvPath: string, fields: Array<keyof T>) {
		const ingestStream = this.postgres.client.query(
			copyFrom(`COPY table_name (field) FROM STDIN WITH (FORMAT csv)`),
		);
		const sourceStream = fs.createReadStream(csvPath);
		try {
			ingestStream.on('error', e => {
				this.logger.error('issues', e);
			});
			return await new Promise((resolve, reject) => {
				sourceStream.on('error', e => {
					reject(e);
				});
				sourceStream.on('end', () => {
					resolve(new Result(true));
				});
				sourceStream.pipe(ingestStream);
			});
		} catch (err) {
			this.logger.error(err);
		} finally {
			ingestStream.end();
			sourceStream.close();
		}
	}
```

what is happening?
I added around 500K rows in a batch of 20k, But all the rows were not inserted and I didn't got any error as well. The row count only increased by around 300K after copying all CSVs.

**Comment by jeromew** [comment]
Hello,
Thanks for the report.

As a first guess, you need to wait for the "finish" event on ingestStream before calling resolve.
maybe something is rollbacking the operation due to the non-waiting on "finish" - it is hard to tell
rows are only visible on postgres after the COPY operation has ended.

**Comment by jeromew** [comment]
cf note on README

**Comment by jeromew** [comment]
cf note on README page at the bottom of section "[pipe from a file to table](https://github.com/brianc/node-pg-copy-streams#pipe-from-a-file-to-table-copyin---copy-from)"

**Comment by Dhruv-Garg79** [comment]
Hey @jeromew thanks for the quick response. 
I already tried all the possible events like end/close/finish, but I am still not getting all the records.

I assumed that either all records in one copy request will get written or all will fail. But some are getting written and some not.

**Comment by Dhruv-Garg79** [comment]
for more information I am using this command to verify if request succeeded.
```
select count(id) from table;
```

using above command I am comparing number of records after and before my script.

**Comment by jeromew** [comment]
indeed you can count lines before / after.

I don't think you should call `ingestStream.end();`

Node.js documentation states

`Calling the writable.end() method signals that no more data will be written to the [Writable](https://nodejs.org/api/stream.html#class-streamwritable)
`
but it is not for you to decide when there is no more data to send.

so :
 - remove `ingestStream.end();`
 - replace `sourceStream.on('end', () => {` by ingestStream.on('finish', () => {``

**Comment by Dhruv-Garg79** [comment]
But should that really cause an issue, since it's in the finally block?
I already replaced, `end` with `finish`, but still issue persists.

**Comment by Dhruv-Garg79** [comment]
I just tried with the suggested changes, but still no help
```ts
public async copyFromCsv(csvPath: string, fields: Array<keyof T>) {
		const ingestStream = this.postgres.client.query(
			copyFrom(`COPY table_name (field) FROM STDIN WITH (FORMAT csv)`),
		);
		const sourceStream = fs.createReadStream(csvPath);
		try {
			ingestStream.on('error', e => {
				this.logger.error('issues', e);
			});
			return await new Promise((resolve, reject) => {
				sourceStream.on('error', e => {
					reject(e);
				});
				sourceStream.on('finish', () => {
					resolve(new Result(true));
				});
				sourceStream.pipe(ingestStream);
			});
		} catch (err) {
			this.logger.error(err);
		}
	}
```

**Comment by jeromew** [comment]
does the `this.logger.debug('ingest stream finished');` print something ?

**Comment by jeromew** [comment]
> But should that really cause an issue, since it's in the finally block? I already replaced, `end` with `finish`, but still issue persists.

sourceStream.on('end') means that the sourceStream has been completely read.
ingestStream.on('finish') means that the ingestStream has completely sent the data to postgres and that postgres has acknowledged the fact that it has received the data and the the COPY operation has ended.

**Comment by jeromew** [comment]
also I don't fully understand the return inside the try/catch block and its consequences.

why don't you use https://nodejs.org/api/stream.html#streampipelinestreams-options

with something like

return pipeline(sourceStream, ingestStream)

**Comment by jeromew** [comment]
Does it work now ?

**Comment by Dhruv-Garg79** [comment]
> does the `this.logger.debug('ingest stream finished');` print something ? do you have any log on the postgres side or the node side ?

yes, it does print the same message to the console.

I wasn't able to find any error logs on postgres side, when I looked. Do you want any specific logs of postgres?

> why don't you use https://nodejs.org/api/stream.html#streampipelinestreams-options
> return pipeline(sourceStream, ingestStream)

because I am still on node.js 14 and will take sometime to migrate to latest version. pipeline is not available in node.js 14

> Does it work now ?

For now I started using insert many, since I wasn't able to make it work

**Comment by jeromew** [comment]
ok I am sorry you could not make it work.
it the 'finish' event is called, the COPY operation should be finished.
The only thing I can see to drill down on your issue is that you create a minimal version of your problem in a test case.

basically the scenario your are trying to do is one of the main objective of this module so I don't see an obvious reason why it wouldn't work for you (works for me and lots of other people). Maybe it is related to what you said at the beginning 'added around 500K rows in a batch of 20k' which is not code-described in your original post.

**Comment by Dhruv-Garg79** [comment]
Hey I tried again today with the updated code like this

```

I just tried with the suggested changes, but still no help

public async copyFromCsv(csvPath: string, fields: Array<keyof T>) {
		const ingestStream = this.postgres.client.query(
			copyFrom(`COPY table_name (field) FROM STDIN WITH (FORMAT csv)`),
		);
		const sourceStream = fs.createReadStream(csvPath);
		try {
			return new Promise((resolve, reject) => {
				pipeline(sourceStream, ingestStream, (res, err) => {
					if (err) reject(err);
					else resolve(res);
				});
			});
		} catch (err) {
			this.logger.error(err);
		}
	}
```

Now, I got this error
```
Error:
TypeError: Cannot read property 'sendCopyFail' of null
    at done (/node_modules/pg-copy-streams/copy-from.js:72:23)
    at CopyStreamQuery.flush (/node_modules/pg-copy-streams/copy-from.js:105:9)
    at CopyStreamQuery.handleCopyInResponse (/node_modules/pg-copy-streams/copy-from.js:145:10)
    at Client._handleCopyInResponse (/node_modules/pg/lib/client.js:395:22)
    at Connection.emit (events.js:400:28)
    at Connection.emit (domain.js:475:12)
    at /node_modules/pg/lib/connection.js:117:12
    at Parser.parse (/node_modules/pg-protocol/src/parser.ts:104:9)
    at TLSSocket.<anonymous> (/node_modules/pg-protocol/src/index.ts:7:48)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
fatal error: all goroutines are asleep - deadlock!
```

**Comment by jeromew** [comment]
The error log points to `self.connection.sendCopyFail(msg)` - Cannot read property 'sendCopyFail' of null
it also means that destroy() was somehow called on ingestStream and that ingestStream decided to rollback the COPY operation because of an error.

are you calling destroy on the ingestStream ?

maybe the use of pipeline leads to a call of destroy.

can you replace the whole block

```
try {
			return new Promise((resolve, reject) => {
				pipeline(sourceStream, ingestStream, (res, err) => {
					if (err) reject(err);
					else resolve(res);
				});
			});
		} catch (err) {
			this.logger.error(err);
		}

```

by 

`return pipeline(sourceStream, ingestStream);`

**Comment by jeromew** [comment]
if you want the try/catch block

try {
   await pipeline(sourceStream, ingestStream);
} catch (err) {
   this.logger.error(err);
}

because in your version, the try/catch only catches errors during the setup phase, and not the streaming phase. adding await here in your async block should catch errors during the streaming phase.

**Comment by Dhruv-Garg79** [comment]
I can't use await on pipeline as it's not available in node.js 14 version, let me try by adding await in front of the promisified version.

> are you calling destroy on the ingestStream ?
nope


This is the new version I tried, but still I didn't got any errors and only about 60% of rows were inserted.

```
import fs from 'fs';
import { promisify } from 'node:util';
import { from as copyFrom } from 'pg-copy-streams';
import stream from 'stream';

const pipeline = promisify(stream.pipeline);

public async copyFromCsv(csvPath: string) {
	try {
		const ingestStream = this.postgres.client.query(
			copyFrom(`COPY table_name (field) FROM STDIN WITH (FORMAT csv)`),
		);
		const sourceStream = fs.createReadStream(csvPath);

		await pipeline(sourceStream, ingestStream);
	} catch (err) {
		this.logger.error(err);
	}
}
```

**Comment by jeromew** [comment]
when you say "I added around 500K rows in a batch of 20k" what does it mean ? do you have a wrapper around the copyFromCsv ?

at this stage I don't see what the problem could be.
some ideas
 - you are copying into a table that has constraints and only some of the rows are accepted
 - your csv has an encoding that is not the accepted encoding of the database
 - a bug in your patching process
 - a bug in the posted code but the last version seems correct to me (thought-process, not tested)

**Comment by Dhruv-Garg79** [comment]
yeah, I do have a wrapper over the copyFromCsv for chunking. The chunking logic can't be flawed because it's working with insert many values approach.

- I don't have any such constraints, for id I am using `gen_random_uuid()`. are you familiar if that might be causing issue?
- I already checked this, shouldn't be the issue. only copying strings
- didn't understood what you meant by patching process?
- Have you recently tried this library in node 14, can this be version specific issue?

**Comment by jeromew** [comment]
I just installed node 14.19.0 and all the tests of the library (which are numerous) are passing. You can never say never, but I don't think this is the problem.

> I don't have any such constraints. For id I am using gen_random_uuid(), are you familiar if that can cause the issue?
not that I know of

>I didn't understand what you meant by the patching process.
sorry I meant batching process.

> The chunking logic can't be flawed because it's working with insert many values approach.

this is different here. for example when you were waiting for the sourceStream.on('end') it could not work because you were sending a new batch before the precendent batch was acknowledged by postgres. Depending on how you do it, you may be overflowing `pg` with requests.

Now that i installed 14.19.0 I can try to reproduce your issue, but I need more information. The fact that you say 80% of the data is inserted can mean
 - in a 20k batch, 80% of lines are inserted (the only way i see this could happen is that postgres reject some lines for whatever reason)
 - among 25 batches of 20k lines, only 80% of the batches go through. For this the batching process could be the culprit, either because they are overwhelming postgres, or because they are pending somewhere.

**Comment by jeromew** [comment]
I suppose you decided to not investigate further on this issue. Can we close it now ?

**Comment by FelipeNFL** [comment]
Hello! Today I had a similar problem and I spent my entire day to find it. It's very stupid, but I recommed to check if somebody has the same problem: the quote. The default param to QUOTE in COPY FROM is double-quote. In my case, there was isolated double-quote in specific parts of the file, so some parts simply disappeared, because them has lost in a field TEXT.

**Comment by Dhruv-Garg79** [comment]
hey @jeromew sorry, I couldn't check it further. And thanks for your support, I will close this issue for now.
There might be some other issue as you and @FelipeNFL pointed out. I will try to find the exact issue. we upgraded to node v18 recently, so I will try again with the new node version.
