### ISSUE TITLE
Streaming between DBs, Uncaught Error (Solved)

### ISSUE THREAD

**Issue by lukas-gitl** [brianc/node-pg-copy-streams#41]
I'm streaming data from one database into another. This works great, however if the source table does not exist this results in an uncaught exception. This only happens when streaming to another db. When streaming to stdout the exception is caught as expected.

_What am I doing wrong? Can you please advice?_

Here is a minimal test case
```javascript
const Pool = require('pg-pool');
const readPool = new Pool({
    host: 'localhost',
    database: 'readDb',
    user: 'postgres',
    password: 'password',
    port: 5432
});
const writePool = new Pool({
    host: 'localhost',
    database: 'writeDb',
    user: 'postgres',
    password: 'password',
    port: 5432
});
const pgCopy = require('pg-copy-streams');
const copyTo = pgCopy.to;
const copyFrom = pgCopy.from;

readPool.connect(function(readErr, readClient, readDone) {
    const readStream = readClient.query(copyTo('COPY non_existing_table TO STDOUT'));
    
    writePool.connect(function(writeErr, writeClient, writeDone) {
        const writeStream = writeClient.query(copyFrom('COPY existing_table FROM STDIN'));
        writeStream.on('error', function (err) {
            console.log(err);
            writeDone(err);
            readDone(err);
        });
        readStream.pipe(writeStream);
        readStream.on('end', function () {
            writeDone();
            readDone();
        });
        readStream.on('error', function (err) {
            console.log(err);
            writeDone(err);
            readDone(err);
        });
    });
});
```

-----------------

Actually just solved this by moving 
```javascript
const readStream = readClient.query(copyTo('COPY non_existing_table TO STDOUT'));
```
into the inner connect.

**Comment by lukas-gitl** [comment]
For reference, the unhandled error message looked like this:
```javascript
events.js:141
      throw er; // Unhandled 'error' event
      ^

error: relation "non_existing_table" does not exist
    at Connection.parseE (.../node_modules/pg/lib/connection.js:543:11)
    at Connection.parseMessage (.../node_modules/pg/lib/connection.js:370:17)
    at Socket.<anonymous> (.../node_modules/pg/lib/connection.js:109:22)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by jeromew** [comment]
Yes the problem is that

    const readStream = readClient.query(copyTo('COPY non_existing_table TO STDOUT'));

will trigger an error becore the connect to writePool is done ; so the error listeners are not yet bound.

You could split the listener on readStream :(not tested)

```
readPool.connect(function(readErr, readClient, readDone) {
    const readStream = readClient.query(copyTo('COPY non_existing_table TO STDOUT'));
    readStream.on('error', function (err) {
         console.log(err);
         readDone(err);
     });
   
    writePool.connect(function(writeErr, writeClient, writeDone) {
        const writeStream = writeClient.query(copyFrom('COPY existing_table FROM STDIN'));
        writeStream.on('error', function (err) {
            console.log(err);
            writeDone(err);
            readDone(err);
        });
        readStream.pipe(writeStream);
        readStream.on('end', function () {
            writeDone();
            readDone();
        });
        readStream.on('error', function (err) {
            writeDone(err);
        });
    });
});
```

Feel free to close the issue as I don't think it is a bug with the library.

**Comment by lukas-gitl** [comment]
Thanks for the update @jeromew! That makes perfect sense.

This might be a good code sample btw as it was not clear initially how to stream between dbs.
