### ISSUE TITLE
piping won't work

### ISSUE THREAD

**Issue by punund** [brianc/node-pg-copy-streams#6]
I am trying the example almost verbatim:

````
   pg = require('pg').native
   copyFrom = require('pg-copy-streams').from

   pg.connect pgURL, (err, pgClient, done) ->

      to = pgClient.query copyFrom 'Copy sf_xxx From Stdin'
      fileStream = fs.createReadStream('/tmp/dump.csv')
      fileStream.pipe(to)
````
The only difference is that I `require('pg').native`.
I am getting

````
_stream_readable.js:583
    var written = dest.write(chunk);
                       ^
TypeError: Object [object Object] has no method 'write'
  at write (_stream_readable.js:583:24)
  at flow (_stream_readable.js:592:7)
  at ReadStream.pipeOnReadable (_stream_readable.js:624:5)
  at ReadStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at onread (fs.js:1563:12)
  at Object.wrapper [as oncomplete] (fs.js:454:17)

**Comment by jeromew** [comment]
OP uses `require('pg').native`. The README clearly states now that pg-copy-streams only work with the javascript bindings (non-native). Closing the issue.
