### ISSUE TITLE
Unexpected PostgreSQL message

### ISSUE THREAD

**Issue by fredmartinssilva** [brianc/node-pg-copy-streams#77]
Hi every one!

I'm tryng do COPY from the sql. A file is generated, but i get error below:

> Error: Unexpected PostgreSQL message Z
index.js:45
    at CopyStreamQuery._transform (/home/fredericosilva/Projetos/pg-copy/node_modules/pg-copy-streams/copy-to.js:78:28)
    at CopyStreamQuery.Transform._read (_stream_transform.js:186:10)
    at CopyStreamQuery.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at CopyStreamQuery.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

My code is this:
`client.connect(function(err, client, done) {
  var stream = client.query(copyTo(`COPY (${config.select}) TO '${config.out_dir}' DELIMITER ';' CSV`));  
  stream.pipe(process.stdout);

  stream.on('end', () =>{
    console.log(`Completed loading data into ${config.out_dir}`);      
    client.end();
  });
  stream.on('error', (e) => {
    console.log(e.stack);
    client.end();
  });
});`

I saw that this is a error generic of the pg-copy-streams.
Someone can help me?

**Comment by fredmartinssilva** [comment]
I saw my error. I use TO file, but be would TO STDOUT in COPY command
